# netlify.toml

[build]
  base = "public/"
  publish = "public/"
  functions = "public/netlify/functions" # Updated path

[[redirects]]
  from = "/api/chatbot/*"
  to = "/.netlify/functions/chatbot/:splat" # No change needed here, it's a URL pattern not a file
